### ISSUE TITLE
not compatible with plone5

### ISSUE THREAD

**Issue by iham** [RedTurtle/collective.permalink#2]
the way "typesUseViewActionInListings" is called is no more useable.

**Comment by iham** [comment]
i would like to do several things:

1) move it to collective (so all can work on it)
2) plone5 instead of plone4
3) javascript to make the click an "added to clipboard"
4) use it as object action instead of document action

**Comment by cekk** [comment]
@iham for the first point: done!

For other points: ok, could be a nice improvement. Feel free to contribute.

I made a 0.x branch that should be the Plone 4 compatibility branch.
